version: "3.9"

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload



  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi